name: Deployment App

on:
  push:
    tags:
      - v**

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd pace-app/share-recipe-foods/
            sudo git pull origin master
            cd ..
            sudo docker compose up -d --build recipe-foods
            sudo docker ps
